// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/kuzane/alertmesh/internal/ai"
	"github.com/kuzane/alertmesh/internal/config"
	"github.com/kuzane/alertmesh/internal/engine"
	"github.com/kuzane/alertmesh/internal/realtime"
	"github.com/kuzane/alertmesh/internal/router"
)

// Injectors from wire.go:

// InitApp is the Wire entry-point.  cfg is loaded and the logger is
// initialised in main before this is called.  rootCtx is the long-lived
// application context (cancelled by main on SIGTERM); it is threaded
// into incident.Service and ai.Orchestrator so their fire-and-forget
// goroutines respect graceful shutdown.
func InitApp(rootCtx context.Context, cfg *config.Config) (*App, error) {
	db, err := ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	rbac := ProvideRBAC(db)
	dispatcher := ProvideDispatcher(db, cfg)
	service := ProvideIncidentService(rootCtx, db, dispatcher, cfg)
	incidentCallback := ProvideIncidentCallback(service)
	resolvedCallback := ProvideResolvedCallback(service)
	pipeline := engine.NewPipeline(db, incidentCallback, resolvedCallback)
	sysconfigService, err := ProvideSysConfig(db, cfg)
	if err != nil {
		return nil, err
	}
	jwtService, err := ProvideJWTService(sysconfigService, cfg)
	if err != nil {
		return nil, err
	}
	wsHub := ai.NewWSHub()
	rtHub := realtime.NewHub()
	container := router.Setup(db, rbac, pipeline, service, wsHub, rtHub, jwtService, sysconfigService, cfg)
	server := ProvideHTTPServer(cfg, container)
	aiHook := ProvideAIDispatchHook(service)
	orchestrator := ai.NewOrchestrator(rootCtx, db, cfg, wsHub, aiHook)
	app := NewApp(cfg, server, orchestrator, pipeline, service, db, rtHub, container)
	return app, nil
}
